#pragma once

#ifdef _QXORM_EXAMPLE
#define QXORM_EXAMPLE_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else // _QXORM_EXAMPLE
#define QXORM_EXAMPLE_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif // _QXORM_EXAMPLE

#ifdef _QXORM_EXAMPLE
#define QX_REGISTER_HPP_QXORM_EXAMPLE    QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QXORM_EXAMPLE    QX_REGISTER_CPP_EXPORT_DLL
#else // _QXORM_EXAMPLE
#define QX_REGISTER_HPP_QXORM_EXAMPLE     QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_QXORM_EXAMPLE     QX_REGISTER_CPP_IMPORT_DLL
#endif // _QXORM_EXAMPLE

